# config
domain: "axibpm-domain"
service: "cadence-frontend"

host: "10.174.18.121:7933"
# сервис из которого берем историю по воркфлоу, текущий статус, проверяем домены и т.п.
# так как cadence работает по протоколу thrift
urlrestservice: "http://10.174.18.121:8088"

appname: "AXI-BPM"
# префикс полного наименования методов бизнес-процессов
prefixworkflowfunc: "github.com/777or666/testgogql-cadence/axibpmWorkflows."
# e-mail рассылка
emailidentity: ""
emailfrom: "___@___"
emailusername: "___@___"
emailpassword: "__"
emailhost: "mail.____"
emailport: "25"

# host: "195.209.35.28:7933"
# urlrestservice: "http://195.209.35.28:8088"

# emailfrom: "k_____@gmail.com"
# emailusername: "k_____@gmail.com"
# emailpassword: "_____"
# emailhost: "smtp.gmail.com"
# emailport: "587"