# config
domain: "axibpm-domain"
# domainId не удалось вытащить из сервиса cadence-web поэтому задаем жестко
domainId: "9d88d286-53e5-452d-93db-4ba8613f229f"
service: "cadence-frontend"
# host: "10.174.18.121:7933"
host: "195.209.35.28:7933"
# сервис из которого берем историю по воркфлоу, текущий статус, проверяем домены и т.п.
# так как cadence работает по протоколу thrift
# urlrestservice: "http://10.174.18.121:8088"
urlrestservice: "http://195.209.35.28:8088"
appname: "AXI-BPM"
prefixworkflowfunc: "github.com/777or666/testgogql-cadence/axibpmWorkflows."
