// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	time "time"
)

type Domain struct {
	Name        string     `json:"name"`
	Status      string     `json:"status"`
	Description *string    `json:"description"`
	OwnerEmail  *string    `json:"OwnerEmail"`
	Workflows   []Workflow `json:"workflows"`
}

type Workflow struct {
	ID            string    `json:"id"`
	RunID         *string   `json:"runId"`
	TaskList      string    `json:"taskList"`
	Name          string    `json:"name"`
	StartTime     time.Time `json:"startTime"`
	CloseTime     time.Time `json:"closeTime"`
	CloseStatus   *string   `json:"closeStatus"`
	HistoryLength *int      `json:"historyLength"`
	JSONHistory   *string   `json:"jsonHistory"`
	Input         *string   `json:"input"`
	Result        *string   `json:"result"`
}
