// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	time "time"
)

type Activity struct {
	ID                  string   `json:"id"`
	ActivityID          string   `json:"activityID"`
	Description         string   `json:"description"`
	Operation           string   `json:"operation"`
	Roles               []string `json:"roles"`
	Starttoclosetimeout int      `json:"starttoclosetimeout"`
	IsDone              bool     `json:"isDone"`
	InWork              bool     `json:"inWork"`
	IsCanceled          bool     `json:"isCanceled"`
	Error               string   `json:"Error"`
}

type Domain struct {
	Name        string     `json:"name"`
	Status      string     `json:"status"`
	Description *string    `json:"description"`
	OwnerEmail  *string    `json:"OwnerEmail"`
	Workflows   []Workflow `json:"workflows"`
}

type Workflow struct {
	ID            string     `json:"id"`
	WorkflowID    string     `json:"workflowId"`
	RunID         string     `json:"runId"`
	TaskList      string     `json:"taskList"`
	Name          string     `json:"name"`
	StartTime     time.Time  `json:"startTime"`
	CloseTime     *time.Time `json:"closeTime"`
	CloseStatus   *string    `json:"closeStatus"`
	HistoryLength *int       `json:"historyLength"`
	JSONHistory   *string    `json:"jsonHistory"`
	Result        *string    `json:"result"`
	IsDone        *bool      `json:"isDone"`
	IsCanceled    *bool      `json:"isCanceled"`
	InWork        *bool      `json:"inWork"`
	Activities    []Activity `json:"activities"`
	CreatedAt     time.Time  `json:"createdAt"`
}
